version = 0.1

[default.deploy.parameters]
stack_name = "vozlab-voice-analysis"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CorsOrigins=\"[\\\"*\\\"]\""
confirm_changeset = false
resolve_s3 = true
